### ISSUE TITLE
"Loading wasm..." doesn't disappear

### ISSUE THREAD

**Issue by RReverser** [rust-analyzer/rust-analyzer-wasm#2]
Looks like there is a conflict between manually created text node in `document.body`, and then Monaco taking over said `document.body`. Instead of a regular text node, it becomes a `<text>` element in `document.body` (which is weird, because it's not even standard HTML element) and then removal fails:

```
Uncaught (in promise) DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

As a result, "Loading wasm..." message never disappears.

**Comment by RReverser** [comment]
@edwin0cheng Hm, still seeing same error in Chrome (but not Firefox), even though the code is clearly up-to-date:

![image](https://user-images.githubusercontent.com/557590/113307841-7b6c2c00-92fd-11eb-8313-ca4c6a13bf72.png)
![image](https://user-images.githubusercontent.com/557590/113307863-80c97680-92fd-11eb-8536-4a6fc3a4aabb.png)
![image](https://user-images.githubusercontent.com/557590/113307894-8757ee00-92fd-11eb-93a2-72128dd987cf.png)

Perhaps, instead of creating a text node, just use `document.body.textContent`? That should be both simpler and reliable.

**Comment by RReverser** [comment]
I'm not sure what's transforming actual text node to a `text` element though, that's super weird.

**Comment by RReverser** [comment]
Oh, looks like it's [JSON Viewer extension](https://chrome.google.com/webstore/detail/json-viewer/gbmdgpbipfallnflgajpaliibnhdgobh) in my Chrome that is doing something dodgy here 🤦‍♂️

**Comment by edwin0cheng** [comment]
Yeah, I can’t reproduce this bug in my pc.

**Comment by RReverser** [comment]
Yeah, removing the extension helped. I've never seen this before, but I guess not everyone uses text nodes directly.
